server:
  ip: localhost
  port: 9999
spring:
  application:
    name: pigSale
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping_pig?serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: abc123
  redis:
    host: 192.168.77.131
    port: 6379
    password: abc123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略空字段

#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ze.pigSale.entity
  configuration:
    map-underscore-to-camel-case: true

pigSale:
  path: D:\temp\
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ze.pigSale.entity
  type-enums-package: com.ze.pigSale.enums