server:
  ip: localhost
  port: 9999
spring:
  application:
    name: pigSale
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping_pig?serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
#    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    username: root
    password: abc123
  redis:
    host: 192.168.77.131
    port: 6379
    password: abc123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略空字段
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: 192.168.77.131:9200
rocketmq:
  name-server: 192.168.77.131:9876
  producer:
    group: pigsale-producerGroup
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

framework:
  fastjson:
    safa-mode: true
  cache:
    redis:
      value-timeout: 50000
      bloom-filter:
        user-register:
          name: user_register_cache_penetration_bloom_filter${unique-name:}

#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ze.pigSale.entity
  configuration:
    map-underscore-to-camel-case: true
#图片存储路径
pigSale:
  path: D:\temp\
#MP
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ze.pigSale.entity
  type-enums-package: com.ze.pigSale.enums